name: crabup toolchain install
author: The Internet
description: Install the Crab toolchain
branding:
  icon: activity
  color: purple

inputs:
  toolchain:
    description: Crab toolchain specification
    required: true
  targets:
    description: Comma-separated list of target triples to install for this toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed
    required: false

outputs:
  cachekey:
    description: A short hash of the crabc version, appropriate for use as a cache key. "20220627a831"
    value: ${{steps.crabc-version.outputs.cachekey}}
  name:
    description: Crabup's name for the selected version of the toolchain. "1.62.0"  # suitable for use with `crabgo +${{steps.toolchain.outputs.name}}`
    value: ${{steps.parse.outputs.toolchain}}

runs:
  using: composite
  steps:
    - id: parse
      run: |
        : parse toolchain version
        if [[ $toolchain =~ ^stable' '[0-9]+' '(year|month|week|day)s?' 'ago$ ]]; then
          if [[ ${{runner.os}} == macOS ]]; then
            echo "toolchain=1.$((($(date -v-$(sed 's/stable \([0-9]*\) \(.\).*/\1\2/' <<< $toolchain) +%s)/60/60/24-16569)/7/6))" >> $GITHUB_OUTPUT
          else
            echo "toolchain=1.$((($(date --date "${toolchain#stable }" +%s)/60/60/24-16569)/7/6))" >> $GITHUB_OUTPUT
          fi
        elif [[ $toolchain =~ ^stable' 'minus' '[0-9]+' 'releases?$ ]]; then
          echo "toolchain=1.$((($(date +%s)/60/60/24-16569)/7/6-${toolchain//[^0-9]/}))" >> $GITHUB_OUTPUT
        else
          echo "toolchain=$toolchain" >> $GITHUB_OUTPUT
        fi
      env:
        toolchain: ${{inputs.toolchain}}
      shell: bash

    - id: flags
      run: |
        : construct crabup command line
        echo "targets=$(for t in ${targets//,/ }; do echo -n ' --target' $t; done)" >> $GITHUB_OUTPUT
        echo "components=$(for c in ${components//,/ }; do echo -n ' --component' $c; done)" >> $GITHUB_OUTPUT
        echo "downgrade=${{inputs.toolchain == 'nightly' && inputs.components && ' --allow-downgrade' || ''}}" >> $GITHUB_OUTPUT
      env:
        targets: ${{inputs.targets || inputs.target || ''}}
        components: ${{inputs.components}}
      shell: bash

    - run: |
        : install crabup if needed
        if ! command -v crabup &>/dev/null; then
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://install.crablang.org" | sh -s -- --default-toolchain none -y
          echo "${CRABGO_HOME:-$HOME/.crabgo}/bin" >> $GITHUB_PATH
        fi
      if: runner.os != 'Windows'
      shell: bash

    - name: crabup toolchain install ${{steps.parse.outputs.toolchain}}
      run: crabup toolchain install ${{steps.parse.outputs.toolchain}}${{steps.flags.outputs.targets}}${{steps.flags.outputs.components}} --profile minimal${{steps.flags.outputs.downgrade}} --no-self-update
      shell: bash

    - run: crabup default ${{steps.parse.outputs.toolchain}}
      shell: bash

    - id: crabc-version
      run: |
        : create cachekey
        DATE=$(crabc +${{steps.parse.outputs.toolchain}} --version --verbose | sed -ne 's/^commit-date: \(20[0-9][0-9]\)-\([01][0-9]\)-\([0-3][0-9]\)$/\1\2\3/p')
        HASH=$(crabc +${{steps.parse.outputs.toolchain}} --version --verbose | sed -ne 's/^commit-hash: //p')
        echo "cachekey=$(echo $DATE$HASH | head -c12)" >> $GITHUB_OUTPUT
      shell: bash

    - run: |
        : disable incremental compilation
        if [ -z "${CRABGO_INCREMENTAL+set}" ]; then
          echo CRABGO_INCREMENTAL=0 >> $GITHUB_ENV
        fi
      shell: bash

    - run: crabc +${{steps.parse.outputs.toolchain}} --version --verbose
      shell: bash

